[tool.poetry]
name = "cdp-action"
version = "0.0.1"
description = "ChromaDB Data Pipes ğŸ–‡ï¸ GH Action"
authors = ["Trayan Azarov <trayan.azarov@amikos.tech>"]
readme = "README.md"
license = "MIT"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/amikos-tech/cdp-action/issues"
"Homepage" = "https://datapipes.chromadb.dev/"
"Source" = "https://github.com/amikos-tech/cdp-action/"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
